services:
  backend:
    build:
      context: ./PoseFit_Trainer/AI_PersonTrainer backend
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./PoseFit_Trainer/AI_PersonTrainer backend:/app
      - backend_data:/app/user_profiles
      - backend_videos:/app/saved_workouts
      - backend_temp:/app/temp_videos
    environment:
      - HOST=0.0.0.0
      - PORT=8002
      - FRAME_INTERVAL=0.033
      - DOWNSCALE_FACTOR=1.0
      - SECRET_KEY=your-secret-key-here
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - TEMP_VIDEOS_DIR=temp_videos
      - SAVED_WORKOUTS_DIR=saved_workouts
      - USER_PROFILES_DIR=user_profiles
      - MEDIAPIPE_DISABLE_GPU=1
      - TF_CPP_MIN_LOG_LEVEL=3
      - MP_MIN_DETECTION_CONFIDENCE=0.5
      - MP_MIN_TRACKING_CONFIDENCE=0.5
      - MP_ENABLE_SEGMENTATION=False
      - MP_MODEL_COMPLEXITY=1
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8002/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 180s
    restart: unless-stopped
    networks:
      - posefit-network
    
  posefit-trainer:
    build:
      context: ./PoseFit_Trainer/personal-trainer-auth
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./PoseFit_Trainer/personal-trainer-auth:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - BACKEND_URL=http://backend:8002
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - posefit-network

  convex:
    build:
      context: ./PoseFit_assistant
      dockerfile: Dockerfile.convex
    volumes:
      - ./PoseFit_assistant:/app
      - /app/node_modules
    command: npx convex dev
    restart: unless-stopped
    networks:
      - posefit-network

  posefit-assistant:
    build:
      context: ./PoseFit_assistant
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_Y29tcG9zZWQtc2N1bHBpbi02MC5jbGVyay5hY2NvdW50cy5kZXYk
        - CLERK_SECRET_KEY=sk_test_fLtgeNhSLuo1ZYP6zr9walZaQKo8wGwLGtIGoVZyQv
        - NEXT_PUBLIC_CONVEX_URL=https://benevolent-cow-710.convex.cloud
    ports:
      - "3001:3000"
    volumes:
      - ./PoseFit_assistant:/app
      - /app/node_modules
    depends_on:
      - convex
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_Y29tcG9zZWQtc2N1bHBpbi02MC5jbGVyay5hY2NvdW50cy5kZXYk
      - CLERK_SECRET_KEY=sk_test_fLtgeNhSLuo1ZYP6zr9walZaQKo8wGwLGtIGoVZyQv
      - NEXT_PUBLIC_CONVEX_URL=https://benevolent-cow-710.convex.cloud
    restart: unless-stopped
    networks:
      - posefit-network

  posefit-landing:
    build:
      context: ./posefit-landing
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    volumes:
      - ./posefit-landing:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - posefit-network

volumes:
  backend_data:
  backend_videos:
  backend_temp:

networks:
  posefit-network: 