name: Deploy Landing Page to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      
      - name: Install dependencies
        working-directory: ./posefit-landing
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          rm -rf node_modules
          npm ci
          npm install next@14.1.0 react@18.2.0 react-dom@18.2.0 tailwindcss@3.3.0 autoprefixer@10.4.16 postcss@8.4.31 --save
      
      - name: Build
        working-directory: ./posefit-landing
        run: |
          npm run build
          touch out/.nojekyll
        env:
          NEXT_TELEMETRY_DISABLED: 1
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: posefit-landing/out
          branch: gh-pages 